#In the folder of the example you have three folder ra, rb and rc, in each folder there is the file Log.final.out generated by STAR
#Write a script that create a table containing as header ra, rb and rc names and as rownames "Uniquely mapped reads number"" 
#and "Number of reads mapped to multiple loci"

#Extract from the files the requested numbers and create the 3 col x 2 row matrix
#saver the matrix a comma separated file


ra <- readLines("C:/Users/seren/Desktop/Exam_sim_1/ra/Log.final.out")
rb <- readLines("C:/Users/seren/Desktop/Exam_sim_1/rb/Log.final.out")
rc <- readLines("C:/Users/seren/Desktop/Exam_sim_1/rc/Log.final.out")
#by typing "ra", "rb" and "rc" you can visualize the file and see which is the index of the sections of interest 
#(e.g., "Uniquely mapped reads number")

#by looking at the appearance of the files it is necessary to separate the numeric values from the description of what they stand for:
ra_s <- strsplit(ra, split ="\t")
rb_s <- strsplit(rb, split ="\t")
rc_s <- strsplit(rc, split ="\t")
#type "ra_s" to see how do they appear now, and to see the indexes. You'll notice they became lists.

#Extract the numbers only (for "Uniquely Mapped Reads Number") and convert them from character to numeric vectors:
ra_char_UMRN <- as.numeric((ra_s[[9]])[2])
rb_char_UMRN <- as.numeric((rb_s[[9]])[2])
rc_char_UMRN <- as.numeric((rc_s[[9]])[2])

#Do the same for "Number of Reads Mapped to Multiple Loci":
ra_char_NRMML <- as.numeric((ra_s[[24]])[2])
rb_char_NRMML <- as.numeric((rb_s[[24]])[2])
rc_char_NRMML <- as.numeric((rc_s[[24]])[2])


matrix <- matrix(
  c(ra_char_UMRN, rb_char_UMRN, rc_char_UMRN, ra_char_NRMML, rb_char_NRMML, rc_char_NRMML),
  nrow = 2,
  ncol = 3,
  byrow = TRUE
)

rownames(matrix) <- c("Uniquely mapped reads number", "Number of reads mapped to multiple loci")
colnames(matrix) <- c("ra", "rb", "rc")

write.csv(matrix, "C:/Users/seren/Desktop/Exam_sim_1/log.fin.out_MATRIX.csv")