var pd_map={image_path:("https:"==document.location.protocol?"https://polldaddy.com":"http://i0.poll.fm")+"/images/ratings"};function PDRTJS_url_encode(e){return encodeURIComponent(e).replace(/%20/g,"+").replace(/!/g,"%21").replace(/'/g,"%27").replace(/\(/g,"%28").replace(/\)/g,"%29").replace(/\*/g,"%2A").replace(/~/g,"%7E")}function PDRTJS_is_defined(e){return"undefined"==typeof e?!1:!0}var ratings_text=[];ratings_text.text_vote="Vote";ratings_text.text_votes="Votes";
ratings_text.text_rate_this="Rate This";ratings_text.text_1_star="1 star";ratings_text.text_2_star="2 stars";ratings_text.text_3_star="3 stars";ratings_text.text_4_star="4 stars";ratings_text.text_5_star="5 stars";ratings_text.text_thank_you="Thank You";ratings_text.text_rate_up="Rate Up";ratings_text.text_rate_down="Rate Down";ratings_text.text_popcontent="Most Popular Content";ratings_text.text_close="Close";ratings_text.text_all="All";ratings_text.text_today="Today";
ratings_text.text_thisweek="This Week";ratings_text.text_thismonth="This Month";ratings_text.text_rated="Rated";ratings_text.text_noratings="There are no rated items for this period";
function PDRTJS_RATING(e){function f(a){return document.getElementById(a)}this.resolution=1<window.devicePixelRatio?"retina":"lowres";var p=("https:"==document.location.protocol?"https:":"http:")+"//polldaddy.com";this.id=parseInt(e.id);this.override=e.override?parseInt(e.override):null;this.unique_id=e.unique_id?e.unique_id.replace(/[^a-z0-9_-]/gi,""):"";this.item_id=e.item_id?e.item_id.replace(/[^a-z0-9_-]/gi,""):"";this.title=e.title?e.title.replace(/[^a-z0-9_-]/gi,""):"";this.permalink=e.permalink?
e.permalink:"";var k=document.createElement("p");k.setAttribute("style","padding: 0px; margin: 0px; clear: both;");var l=0;this.make_call=function(a){null!=this.override&&(a+="&override=true");var b=document.createElement("SCRIPT");b.charset="utf-8";b.src=p+a;document.getElementsByTagName("head").item(0).appendChild(b)};this.callback=function(a,b,c,d,f,e){null!=this.callback_url&&(a=this.callback_url.replace(/{id}/,a),a=a.replace(/{unique_id}/,b),a=a.replace(/{type}/,c),a=a.replace(/{r}/,d),a=a.replace(/{voter_id}/,
f),a="stars"==c?a.replace(/{scores}/,this.votes+","+this.avg_rating):a.replace(/{scores}/,this.nero_up+","+this.nero_dn),e&&(a+="&change=true"),b=document.createElement("SCRIPT"),b.charset="utf-8",b.src=a,document.getElementsByTagName("head").item(0).appendChild(b))};this.get_rating=function(){this.varname="PDRTJS_"+this.id+this.item_id;this.make_call("/ratings/rate.php?cmd=get&id="+this.id+"&uid="+this.unique_id+"&item_id="+this.item_id)};this.init=function(a){for(var b in a)this[b]=a[b];this.build()};
this.build=function(){this.font=this.font_italic+" "+this.font_bold+" "+this.font_size+"/"+this.font_line_height+" "+this.font_family;this.p=document.createElement("div");this.p.style.display="inline-block";this.star_margin="1px";this.custom_star&&0<this.custom_star.length?(this.star_image=this.custom_star,this.star_margin="1px"):(this.star_image=pd_map.image_path,this.star_image="stars"==this.type?"retina"==this.resolution?this.star_image+("/star-"+this.star_color+"-"+this.size+"@2x.png"):this.star_image+
("/star-"+this.star_color+"-"+this.size+".png"):"retina"==this.resolution?this.star_image+("/nero-"+this.star_color+"-"+this.size+"@2x.png"):this.star_image+("/nero-"+this.star_color+"-"+this.size+".png"));this.image_sizes={nero:{lowres:{sml:{width:"16px",height:"16px",bg_width:"32px",bg_height:"32px"},med:{width:"20px",height:"20px",bg_width:"40px",bg_height:"40px"},lrg:{width:"24px",height:"24px",bg_width:"48px",bg_height:"48px"}},retina:{sml:{width:"16px",height:"16px",bg_width:"32px",bg_height:"32px"},
med:{width:"32px",height:"32px",bg_width:"64px",bg_height:"64px"},lrg:{width:"48px",height:"48px",bg_width:"96px",bg_height:"96px"}}},stars:{lowres:{sml:{width:"16px",height:"16px",bg_width:"32px",bg_height:"48px"},med:{width:"20px",height:"20px",bg_width:"40px",bg_height:"60px"},lrg:{width:"24px",height:"24px",bg_width:"48px",bg_height:"72px"}},retina:{sml:{width:"16px",height:"16px",bg_width:"32px",bg_height:"48px"},med:{width:"20px",height:"20px",bg_width:"40px",bg_height:"60px"},lrg:{width:"24px",
height:"24px",bg_width:"48px",bg_height:"72px"}}}};if("stars"==this.type){var a="bottom left",b=this.text_rate_this;0<this.votes&&(a="top left",b=this.votes+" ",b=1==this.votes&&"undefined"!=typeof this.text_vote?b+this.text_vote:b+this.text_votes);var c=document.createElement("div");c.setAttribute("class","rating-msg");c.setAttribute("id",this.varname+"_msg");"right"==this.font_position?c.setAttribute("style","float:left; padding-left: 5px; text-align: "+this.font_align+"; font:"+this.font+"; color: #"+
this.font_color+";"):c.setAttribute("style","text-align: "+this.font_align+";font:"+this.font+";color: #"+this.font_color+";");b=document.createTextNode(b);c.appendChild(b);"top"==this.font_position&&(this.p.appendChild(c),this.p.appendChild(k));icons_part=document.createElement("div");icons_part.setAttribute("class","rating-icons");icons_part.setAttribute("id","pd_rate_"+this.id+this.item_id);icons_part.setAttribute("style","float:left;");for(var d=1;5>=d;d++)0<this.avg_rating&&(this.avg_rating<
d&&(a="bottom left"),this.avg_rating==d-1+.5&&(a="center left")),part=document.createElement("div"),part.setAttribute("class","rating-star-icon"),part.setAttribute("onmouseout",this.varname+".rebuild()"),part.setAttribute("onclick",this.varname+".rate( "+d+" )"),part.setAttribute("onmouseover",this.varname+".hover("+d+")"),part.setAttribute("id",this.varname+"_stars_"+d),part.setAttribute("style","background-size:"+this.image_sizes[this.type][this.resolution][this.size].bg_width+" "+this.image_sizes[this.type][this.resolution][this.size].bg_height+
" !important; cursor: pointer; width: "+this.image_sizes[this.type][this.resolution][this.size].width+"; height: "+this.image_sizes[this.type][this.resolution][this.size].width+"; line-height: "+this.image_sizes[this.type][this.resolution][this.size].height+"; background: url("+this.star_image+") "+a+"; float: left; padding: 0px; margin: 0px; margin-right: "+this.star_margin+";"),b=document.createTextNode(" "),part.appendChild(b),icons_part.appendChild(part)}else for(a="left",b=[],b[0]=this.text_rate_this,
b[1]="",b[2]="",null!=this.nero_up?b[1]=this.nero_up:(this.nero_up=0,b[1]="0"),null!=this.nero_dn?b[2]=this.nero_dn:(this.nero_dn=0,b[2]="0"),c=document.createElement("div"),c.setAttribute("class","rating-msg"),c.setAttribute("id",this.varname+"_msg"),"right"==this.font_position?c.setAttribute("style","float:left; padding-left: 5px; text-align: "+this.font_align+"; font:"+this.font+";color: #"+this.font_color+";"):c.setAttribute("style","text-align: "+this.font_align+"; font:"+this.font+"; color: #"+
this.font_color+";"),d=document.createTextNode(b[0]),c.appendChild(d),"top"==this.font_position&&(this.p.appendChild(c),this.p.appendChild(k)),icons_part=document.createElement("div"),icons_part.setAttribute("class","rating-icons"),icons_part.setAttribute("id","pd_rate_"+this.id+this.item_id),icons_part.setAttribute("style","float:left;"),d=1;2>=d;d++){2==d&&(a="right");part=document.createElement("div");part.setAttribute("class","rating-nero-icon");part.setAttribute("onmouseout",this.varname+".rebuild()");
part.setAttribute("onclick",this.varname+".rate( "+d+" )");part.setAttribute("onmouseover",this.varname+".hover("+d+")");part.setAttribute("id",this.varname+"_nero_"+d);part.setAttribute("style","background-size: "+this.image_sizes[this.type][this.resolution][this.size].bg_width+" "+this.image_sizes[this.type][this.resolution][this.size].bg_height+" !important; cursor: pointer; width: "+this.image_sizes[this.type][this.resolution][this.size].width+";height: "+this.image_sizes[this.type][this.resolution][this.size].height+
";  line-height: "+this.image_sizes[this.type][this.resolution][this.size].height+";background: url("+this.star_image+") bottom "+a+"; float: left; padding: 0px; margin: 0px; margin: 0px;");var e=document.createTextNode(" ");part.appendChild(e);icons_part.appendChild(part);part=document.createElement("div");part.setAttribute("class","rating-nero-value");part.setAttribute("id",this.varname+"_msg_"+d);part.setAttribute("style","text-align: center; font:"+this.font+"; color: #"+this.font_color+";float:left; padding: 0px 4px;");
e=document.createTextNode(b[d]);part.appendChild(e);icons_part.appendChild(part)}this.p.appendChild(icons_part);this.buildPopup();"bottom"==this.font_position?(this.p.appendChild(k),this.p.appendChild(c),this.p.appendChild(k)):"right"==this.font_position&&(this.p.appendChild(c),this.p.appendChild(k));this.p.setAttribute("id","pd_rating_holder_"+this.id+this.item_id);f("pd_rating_holder_"+this.id+this.item_id).replaceWith(this.p)};this.buildPopup=function(){var a=!0;"off"==this.popup&&(a=!1,this.get_results(99));
if(null==f("pd_popup_holder_"+this.id+this.item_id)){var b="#pd_popup_holder_"+this.id+this.item_id+" { position:absolute; display:none; width:"+(a?"350":"175")+"px; height:auto; top:0px; left:0px; z-index:10000; border:solid 1px #CCC; background-color:white; padding:0px 15px;font-family:Arial,Sans;box-shadow: -10px 10px 20px rgba(0, 0, 0, .5);-webkit-box-shadow: 0px 0px 6px rgba(0, 0, 0, .25);-moz-box-shadow: 0px 0px 6px rgba(0, 0, 0, .25); }",c=document.createElement("style");c.setAttribute("type",
"text/css");c.setAttribute("id","pd_popup_holder_style_"+this.id+this.item_id);c.styleSheet?c.styleSheet.cssText=b:c.appendChild(document.createTextNode(b));document.getElementsByTagName("head").item(0).appendChild(c)}c="/info.png";var d=null;"retina"==this.resolution&&(c="/info@2x.png",d="background-size:12px 12px;");t=document.createElement("span");t.setAttribute("style","float:left");b=document.createTextNode(" ");t.appendChild(b);this.p.appendChild(t);t=document.createElement("div");t.setAttribute("id",
"rating_info_"+this.id+this.item_id);t.setAttribute("style","display:"+(a?"block":"none")+";float:left;background:url("+pd_map.image_path+c+") no-repeat 3px 2px;width:16px;height:16px;cursor:pointer; "+d);t.setAttribute("onclick",this.varname+".togglePopup();return false;");c=document.createElement("span");c.setAttribute("style","display:none;");b=document.createTextNode("i");c.appendChild(b);t.appendChild(c);this.p.appendChild(t);t=document.createElement("div");t.setAttribute("class","pd_popup_holder");
t.setAttribute("id","pd_popup_holder_"+this.id+this.item_id);b=document.createTextNode(" ");t.appendChild(b);this.p.appendChild(t)};this.togglePopup=function(){var a=f("pd_popup_holder_"+this.id+this.item_id);"block"==a.style.display?(a.style.display="none",f("rating_info_"+this.id+this.item_id).style.border=""):this.get_results(0)};this.showPopup=function(){var a=f("pd_popup_holder_"+this.id+this.item_id),b=f("rating_info_"+this.id+this.item_id);a.style.display="block";var c=this.getElementPos(b),
d=this.getElementSize(b),e=this.getViewPos(),n=this.getViewSize(),g=this.getElementSize(a),h=f("pd_rate_"+this.id+this.item_id).offsetWidth+2,m=b=c[0]-h,k=n[0],l=e[0],q=g[0],p=d[0];m+q-l>k&&(m=m+h-q+p,m<k+l&&0<m&&(b=m));d=d[1]+2;m=c=c[1]+d;n=n[1];e=e[1];g=g[1];m+g-e>n&&(g=m-d-g,g<n+e&&0<g&&(c=g));a.style.left=b+"px";a.style.top=c+"px"};this.popdown=function(a){f("pd_popup_holder_"+this.id+this.item_id).style.display="none"};this.getElementPos=function(a){var b=a,c=0,d=0;if(b.offsetParent){do c+=b.offsetLeft,
d+=b.offsetTop;while(b=b.offsetParent)}for(;(a=a.parentNode)&&"BODY"!==a.nodeName.toUpperCase();)c-=a.scrollLeft,d-=a.scrollTop;return[c,d]};this.getElementSize=function(a){return[a.offsetWidth,a.offsetHeight]};this.getViewPos=function(){return"number"===typeof window.pageYOffset?[window.pageXOffset,window.pageYOffset]:document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:document.body&&
(document.body.scrollLeft||document.body.scrollTop)?[document.body.scrollLeft,document.body.scrollTop]:[0,0]};this.getViewSize=function(){return"number"===typeof window.innerWidth?[window.innerWidth,window.innerHeight]:document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?[document.documentElement.clientWidth,document.documentElement.clientHeight]:document.body&&(document.body.clientWidth||document.body.clientHeight)?[document.body.clientWidth,document.body.clientHeight]:
[0,0]};this.get_results=function(a){var b="",c="";"undefined"!==typeof document.lastChild.attributes&&null!=document.lastChild.attributes&&"undefined"!==typeof document.lastChild.attributes.dir&&null!=document.lastChild.attributes.dir&&(c="&dir="+document.lastChild.attributes.dir.textContent);for(var d in ratings_text)PDRTJS_is_defined(this[d])&&this[d]!=ratings_text[d]&&(b+="&"+d+"="+PDRTJS_url_encode(this[d]));d=this.id;null!=this.override&&(d=this.override);this.make_call("/ratings/rating-results.php?id="+
d+"&item_id="+this.item_id+"&period="+a+"&item_count=3"+("off"==this.popup?"&off":"")+b+c)};this.rebuild=function(){this.kill_hover||(this.timeout_id=setTimeout(this.varname+".build()",800))};this.cancel_rebuild=function(){null!=this.timeout_id&&(clearTimeout(this.timeout_id),this.timeout_id=null)};this.rate=function(a){if(!this.kill_hover){var b=this.get_voter_id();"stars"==this.type?f(this.varname+"_msg").textContent=this.text_thank_you:(f(this.varname+"_msg").textContent=this.text_thank_you,0==
b&&(1==a?f(this.varname+"_msg_1").textContent=this.nero_up+1:f(this.varname+"_msg_2").textContent=this.nero_dn+1));this.kill_hover=!0;var c="stars"==this.type?"&votes="+this.votes+"&avg="+this.avg_rating:"&up="+this.nero_up+"&down="+this.nero_dn;b=0!=b?"&cmd=change&vid="+PDRTJS_url_encode(b):"&cmd=rate";a="/ratings/rate.php?title="+PDRTJS_url_encode(this.title)+"&permalink="+PDRTJS_url_encode(this.permalink)+"&type="+this.type+"&id="+this.id+"&r="+a+"&uid="+this.unique_id+"&item_id="+this.item_id+
c+b+"&token="+this.token;this.make_call(a);setTimeout(this.varname+".build()",2E3);setTimeout(this.varname+".kill_hover = false",6E3)}};this.hover=function(a){if(!this.kill_hover)if("stars"==this.type){this.cancel_rebuild();for(l=1;5>=l;l++)l<=a?f(this.varname+"_stars_"+l).style.background="url("+this.star_image+") top right / "+this.image_sizes[this.type][this.resolution][this.size].bg_width+" "+this.image_sizes[this.type][this.resolution][this.size].bg_height:f(this.varname+"_stars_"+l).style.background=
"url("+this.star_image+") bottom right / "+this.image_sizes[this.type][this.resolution][this.size].bg_width+" "+this.image_sizes[this.type][this.resolution][this.size].bg_height;f(this.varname+"_msg").textContent=this["text_"+a+"_star"]}else{this.cancel_rebuild();var b=" top left",c=this.text_rate_up;2==a&&(b=" top right",c=this.text_rate_down);f(this.varname+"_nero_"+a).style.background="url("+this.star_image+") "+b+" / "+this.image_sizes[this.type][this.resolution][this.size].bg_width+" "+this.image_sizes[this.type][this.resolution][this.size].bg_height;
f(this.varname+"_msg_"+a).style.fontWeight="bold";f(this.varname+"_msg").textContent=c}};this.set_voter_id=function(a){if(null!=this.voter_id){var b="function"==typeof pd_rating_size?pd_rating_size():1E3,c="function"==typeof pd_cookie_size?pd_cookie_size():4E3;if(document.cookie.length>c){var d=document.cookie.split(";");c=[];for(var e=0,f=0,g=0;g<d.length;g++){var h=d[g];-1!=h.indexOf("PDRTJS_")&&(h=h.replace(/^\s\s*/,"").replace(/\s\s*$/,""),f+=h.length,c[e++]=h)}if(f>b)for(g=0;g<c.length&&!(h=
c[g],f-=h.length,d=h.indexOf("="),0<d&&(h=unescape(h.substring(0,d))),document.cookie=h+"=0;expires=Thu, 01-Jan-1970 00:00:01 GMT;path=/;",f<b);g++);}a="undefined"==typeof a?30:parseInt(a);b=new Date;b.setTime(b.getTime());a*=864E3;a=new Date(b.getTime()+a);b="PDRTJS_"+this.type+"_"+this.id+(0<this.item_id.length?this.item_id:escape(this.unique_id));document.cookie=b+"="+escape(this.voter_id)+";expires="+a.toGMTString()+";path=/;"}};this.get_voter_id=function(){var a="PDRTJS_"+this.type+"_"+this.id+
(0<this.item_id.length?this.item_id:escape(this.unique_id)),b=""+document.cookie,c=b.indexOf(a+"=");if(-1==c||""==a)return 0;var d=b.indexOf(";",c);-1==d&&(d=b.length);return unescape(b.substring(c+a.length+1,d))};this.is_secure=function(){return"https:"==document.location.protocol?!0:!1};null==this.item_id&&(this.item_id="");this.get_rating()}
for(var PDRTJS_doc=document.getElementsByTagName("div"),PDRTJS_id="",i=0;i<PDRTJS_doc.length;i++)if("pd_rating_holder_"==PDRTJS_doc[i].id.substring(0,17)){PDRTJS_id=PDRTJS_doc[i].id.replace(/pd_rating_holder_/,"").replace(/[^a-z0-9_]/gi,"");try{eval("if ( typeof PDRTJS_"+PDRTJS_id+" == 'undefined' ){PDRTJS_"+PDRTJS_id+" = new PDRTJS_RATING( PDRTJS_settings_"+PDRTJS_id+" );}")}catch(e){console.log("Error loading rating for "+PDRTJS_id+": "+e.message)}};
